Feature/SS-6: Provision SMS authentication
dubstep-warrior/smashsync-backend pull request #4
Opened 2024-06-02 14:43 UTC by dubstep-warrior

**Summary**
This pull request introduces SMS authentication to the SmashSync project. It includes an authentication provider interface and implementation using the Twilio client, an authentication use case struct providing functionalities to retrieve and authenticate OTPs, two handler endpoints for these use cases, generated Swagger API specifications, and generated mocks for unit testing.

**Motivation**
To enhance security and provide a seamless user experience, implementing SMS authentication is crucial. This ensures that users can authenticate via OTPs sent to their phone numbers. Additionally, generating JWTs upon successful authentication will help maintain secure sessions.

**Changes**
- Authentication Provider Interface & Implementation: Provides SMS authentication via the Twilio client.
- Authentication Use Case Struct: Includes functionalities to retrieve and authenticate OTPs, returning a JWT token on successful authentication.
- Authentication Handler Endpoints: Corresponding handler end points for authentication use cases.
- Swagger API Specs: Generated API documentation for Auth handlers using Swagger.
- Generated Mocks: Mocks for EchoContext, Logger, SMSProvider, and UserRepository to facilitate isolated unit testing.

2024-06-03 08:21 UTC, YeongZhenHong requested changes

2024-06-03 08:21 UTC, YeongZhenHong commented on smashsync-go/cmd/rest/main.go
> +func init() {
Missing comments

2024-06-03 08:21 UTC, YeongZhenHong commented on smashsync-go/cmd/rest/main.go
> +func addRoutes(e *echo.Echo) {
Missing comments on routes

2024-06-03 08:21 UTC, YeongZhenHong commented on smashsync-go/cmd/rest/main.go
> +	e.GET("/health", func(c echo.Context) error {
Avoid using get, if possible use post over get as get is less secure

2024-06-03 08:54 UTC, dubstep-warrior commented on smashsync-go/cmd/rest/main.go
> +func addRoutes(e *echo.Echo) {
Updated with comments

2024-06-03 08:58 UTC, dubstep-warrior commented on smashsync-go/cmd/rest/main.go
> +	e.GET("/health", func(c echo.Context) error {
Updated Auth endpoints, handlers and corresponding swagger docs.

2024-06-03 09:01 UTC, dubstep-warrior commented on smashsync-go/cmd/rest/main.go
> +func init() {
Updated with comments

2024-06-03 10:55 UTC, YeongZhenHong requested changes

2024-06-03 10:55 UTC, YeongZhenHong commented on smashsync-go/docs/swagger.json
> +                    "multipart/form-data"
JSON as request payload or form data? Inconsistent request types

2024-06-03 10:55 UTC, YeongZhenHong commented on smashsync-go/cmd/rest/main.go
> +	e.GET("/health", func(c echo.Context) error {
JSON as request payload or form data?

2024-06-03 14:59 UTC, dubstep-warrior commented on smashsync-go/docs/swagger.json
> +                    "multipart/form-data"
Updated to JSON payload

2024-06-04 04:00 UTC, YeongZhenHong approved these changes

2024-06-04 04:01 UTC, merged