Feature/SS-9: Provision user profile
dubstep-warrior/smashsync-backend pull request #7
Opened 2024-06-09 12:42 UTC by dubstep-warrior

Reopening PR for [Feature/SS-9: Provision user profile](https://github.com/dubstep-warrior/smashsync-backend/pull/6)

- [x] Get own user profile
- [ ] Update user profile

2024-06-20 12:37 UTC, YeongZhenHong requested changes

2024-06-20 12:37 UTC, YeongZhenHong commented on smashsync-go/rest/v1/middleware/authentication.go
> +			c.Logger().Infoj(map[string]any{
Change to log debug. Unless this is meant to show up.. ?

2024-06-20 14:29 UTC, dubstep-warrior commented on smashsync-go/rest/v1/middleware/authentication.go
> +			c.Logger().Infoj(map[string]any{
Yes, we intend to have logging at an info level for our staging environments, where we can ensure all operations are functioning smoothly. We can eventually bring in debugging logs for variable states that are essential to capture.

2024-06-20 14:29 UTC, dubstep-warrior commented on smashsync-go/rest/v1/middleware/authentication.go
> +				return httperrors.ErrUnauthorized
Updated http errors in latest commit

2024-06-22 09:15 UTC, YeongZhenHong approved these changes

2024-06-22 09:15 UTC, merged